return {
    '🤖 Calling Reinforcements 😈 Spawn 🤫 On Me ❗',
    '🤖 Why havent 😂 You Joined 😯 gg.phantomforces 💀 Bad Player ⚠️',
    'votekick him!!!!!!! 😠 VOTEKICK HIM!!!!!!!!! 😠 😢 VOTE KICK !!!!! PRESS Y WHY DIDNT U PRESS Y!!!!!! 😭',
    "Dont Worry ❌👍 I'm SMURFING‼",
    '😦 I Guess ❌ Nobody Can Read 😡',
    'I NEED ACCESS 🔑🔓 TO RADIANT 🤖📃📃📃 👈 THIS THING CALLED RADIANT, I NEED IT',
    'before i user radiant: 😔😭🙁 after i user radiant: 💸😎📈',
    "i wish i had radiant..... ",
    "can't hear you over these kill sounds",
    "I'm Just Built Different 🧱🧱🧱",
    "how does it feel to not have radiant 🤣🤣🤣😂😂😹😹😹",
    "PRESS Y!!!! PRESS Y Y Y Y!!!!!!!",
    "Jraine gangg ⛓️🩸⛓️🩸",
    "If its a depot got a bite it🥶🥶🥶",
    "gg.phantomforces | gg.phantomforces | gg.phantomforces",
    "Wheres your radiocarthology access NN?",
    "HOw do you get ACCESS to this SCRIIPT???!!?😔😔 TELL ME NOW!!😡😡 ",
    "clipped that 🤡",
    "report him!11!!😡😡😡 omghs report!!😠😠😠 do /report!!😱😱😱",
    "Why the hekk does this freeaky conveersation use an excessive amount of emojis😱😱😱😱😱??!??",
    'WE THE BEST CHEATS 🔥🔥🔥🔥',
    'DJ KHALID UID 3',
    'Ehub winning!!!!!!!!!',
    'OFF📈THE📈CHART📈',
    'KICK HIM 🦵🦵🦵',
    '😂😂😂😂😂GAMING CHAIR😂😂😂😂😂',
    'brb taking a nap 💤💤💤',
    'WHAT SCRIPT IS THAT????',
    'Doood what is this radiant thing',
    '🥱 This☝️Is Cringe 😬  But Lowkey 🔑 Entertaining 📺',
    '🦉🦉🦉🦉🦉🦉Keep yur hands wher i can see em 🦉🦉🦉🦉🦉🦉',
    '🦉🦉🦉🦉🦉🦉🦉🦉🦉🦉🦉🦉',
    'god i wish i had radiant..... 🙏🙏🥺🥺🥺',
    '🤓🤓 Im reporting you 🫵 to 😎 stylis studios for 🤫 CHEeTING! 😱',
    'LOOK BRO LOOK AT ME 😂    HAHA MADE U LOOK! 😯 😡',
    '🧱🧱🧱🧱🧱🧱',
}
